### ISSUE TITLE
Idea: ignore by branch prefix - env var?

### ISSUE THREAD

**Issue by eidam** [kiwicom/plzrebase#1]
@chauffer Can we somehow set branches prefix which will be ignored? I mean, I have now release candidate which we didn't release on time - postponed to next week and it's already 50 commits behind - in case I will need to build again (f.e. actual translations) it wouldn't let me continue in the pipeline (release to staging for QAs)

**Comment by iakat** [comment]
Sure, why not. :D

**Comment by eidam** [comment]
👏
